# Generated by Django 4.0 on 2024-05-28 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Фильтр')),
            ],
            options={
                'verbose_name': 'Filter',
                'verbose_name_plural': 'Filters',
                'db_table': 'filter',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Картинка к задаче')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'db_table': 'Image',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Условие задачи')),
                ('solution', models.TextField(null=True, verbose_name='Решение задачи')),
                ('answer', models.CharField(max_length=50, null=True, verbose_name='Ответ задачи')),
                ('filters', models.ManyToManyField(to='ModelsApp.Filter', verbose_name='Фильтры')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'db_table': 'Task',
            },
        ),
        migrations.CreateModel(
            name='TaskImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Task', 'картинка в условии'), ('Answer', 'картинка в ответе')], default='Task', max_length=6, verbose_name='Где отображать картинку')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModelsApp.image', verbose_name='Картинка')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModelsApp.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'TaskImage',
                'verbose_name_plural': 'TaskImages',
                'db_table': 'TaskImage',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='images',
            field=models.ManyToManyField(through='ModelsApp.TaskImage', to='ModelsApp.Image', verbose_name='Картинки'),
        ),
    ]
